### ISSUE TITLE
Reject an incoming call if there is an ongoing  Call

### ISSUE THREAD

**Issue by croufay** [RestComm/restcomm-web-sdk#97]
@antonis I need your input on this ticket about a question for WebRTC. Is is possible to reject an incoming call while you are currently on a call ?

@charles managed to test this so the way it works right now is that on second call while 1st is ongoing you get ringing and from then on it messes up: If you decline it closes the 1st call's controls but media is still there

**Comment by atsakiridis** [comment]
Fixed with https://github.com/RestComm/webrtcomm/issues/79
